#!/bin/bash

COUNTRIES=(
  "United_States"
  "United_Kingdom"
  "Germany"
  "Canada"
  "Australia"
  "Netherlands"
  "France"
  "Sweden"
  "Japan"
  "Singapore"
)



while true; do
  clear
  RAND=${COUNTRIES[$RANDOM % ${#COUNTRIES[@]}]}
  echo "🌍 Connect VPN ke: $RAND"
  nordvpn c "$RAND"

  echo "🚀 Menjalankan Proxy Bot..."
  python proxy.py
done
